# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8e4416d616e96ea0a8b5468b54845d73ff919025ac3834cf458bf591ca663ce158edf2b664204ee694f65bcfa0900be9d919ddad0cb4342306ccac597cbb28aa

test:
  secret_key_base: 1bdaf281aac115724b6cdfcb4236df40b2f313c3e650da26b32f618348ff03511d08c1aace67f8e1d1bf819d3ff348ee4b87877b5155cac9b7116304b11ad674

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
